name: Github Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: "Hello World"
      - name: Print Goodbye
        run: "GoodBye"
